### ISSUE TITLE
RFC DoC Autosave Turn 8 Bablyon Glitch

### ISSUE THREAD

**Issue by 1SDANi** [dguenms/Dawn-of-Civilization#141]
*Copy pasted from the attatched .txt glitch explaination file*

Found a glitch in the Civ 4 mod RFC Dawn of Civilization's hrtechs branch latest version revision 3320 downloaded on 1/17/2017

The glitch is caused by playing as Babylon and gaining a free tech, 
then while still in the same game instance load a previous state of the same game.
The game still has memory of you gaining a free tech previously and you do not get to choose a free tech.
Opening in a new game instance or loading the autosave from a separate instance does not seem to be affected by this glitch.
Normal save games seem to not be affected, only autosaves.

To reproduce in the attatched autosave:
	1) End turn and pick free tech
	2) Load autosave through in-game menu
	3) End turn
	4) It should state that the last free tech was picked turn 9

[RFC DoC Autosave Turn 8 Bablyon Glitch.zip](https://github.com/dguenms/Dawn-of-Civilization/files/712075/RFC.DoC.Autosave.Turn.8.Bablyon.Glitch.zip)

**Comment by dguenms** [comment]
Looks like I didn't completely think through how to persist this effect. I've made a note to look into it. Thanks for the detailed description including save and steps for reproduction.

**Comment by dguenms** [comment]
Did you mean for me to load the autosave from turn 8? Continuing from your save I only have turn 9, where I have already received the tech, and as you say loading normal saves does not produce the same problem. So I couldn't reproduce the issue.

However, it is most likely a bug that I fixed a couple days ago on the develop branch. I just rebased hrtechs to develop so hopefully this issue should also be taken care of now. If you want to confirm, please let me know here. The savegames should still be compatible.

**Comment by 1SDANi** [comment]
Just played to turn 8 on a new game, reloaded after getting a tech and choosing a free one, and I didn't get the option for a free tech. It's still happening.

You are indeed supposed to load from turn 8. Then you go to turn 9, get the tech and the free tech. Reload the autosave of turn 8 through the ingame menu, and progress to turn 9 again. You should find that you don't get to choose a free tech this time.

EDIT: It just occured to me that you may not have an autosave due to turn 8 being the turn you start from. You should be able to reproduce the error just by going through a normal game as Babylon and after getting your first tech reloading to before you got the tech and continuing until you get it.

**Comment by dguenms** [comment]
Yeah that was exactly the issue, I basically joined your game after the autosave would have been created. But it's no problem, I can just play until then and recreate the situation myself.

**Comment by dguenms** [comment]
Okay I know what's wrong now, it will take me some time to fix this the right way though.

**Comment by 1SDANi** [comment]
Thanks

**Comment by dguenms** [comment]
Okay, so I'm pretty sure it's fixed now; at least your scenario is working now.

**Comment by 1SDANi** [comment]
Yay! Now I don't have to waste the five seconds it takes to go to the main menu and reload my game every time I feel like a save scumming cheapshot!

But seriously, thanks for fixing it.

EDIT On the note of save scumming is it possible to set reminders in this mod? Would really help me not forget my strategy every 5 turns.

**Comment by dguenms** [comment]
Oh, it was actually more than that. There was a conflict between the DoC saved data and the BUG saved data, apparently DoC seemed to win out in most cases (and your case was the exception) but that means that BUG often was partially malfunctioning in the background. So I actually discovered and fixed a pretty significant issue because of your report.

And speaking of BUG, I think you can also use it to set reminders.

**Comment by 1SDANi** [comment]
Wow. That's far more major of a bug than I thought.

On the side of reminders, that's awesome!
